### ISSUE TITLE
Error in workflow 'Alfred Books' – tuple index out of range

### ISSUE THREAD

**Issue by jirir** [codycodes/alfred-books#9]
It says:
 
—————————
Error in workflow 'Alfred Books'
tuple index out of range
 
![Screen Shot 2019-09-13 at 13 42 10](https://user-images.githubusercontent.com/20031425/64860386-44f09280-d62d-11e9-83ba-ee6f0a63c6b4.png)

—————————
macOS 10.13.6
Alfred 4.0.3

**Comment by codycodes** [comment]
Thanks for opening this issue. I'm going to need more information to solve this issue. Can you please generate a detailed log by following these instructions? https://www.alfredforum.com/topic/10224-reporting-problems-with-workflows/

**Comment by codycodes** [comment]
Hello! If you're still having this issue feel free to post logs. I haven't been able to reproduce it on my end 
and haven't yet seen other user's reports, so I'm going to close this issue.
